version: "3.0"
services:
    # Candidate:
    #   container_name: candidat-service
    #   build: ./candidat-service
    #   ports:
    #     - "8045:8045"
    #   hostname: candidate
    #   environment:
    #     - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    #   image: "candidate-service" 
    #   depends_on: 
    #     - Eureka



    # Evaluation:
    #   container_name: evaluation-service
    #   build: ./evalulation-service
    #   ports:
    #     - "8085:8085"
    #   hostname: evaluation
    #   environment:
    #     - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    #   image: "evaluation-service"
    #   depends_on:
    #     - Eureka

    # Offre:
    #   container_name: offre-service
    #   build: ./offre-service
    #   ports:
    #     - "8086:8086"
    #   hostname: offre
    #   environment:
    #     - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    #   image: "offre-service"
    #   depends_on:
    #     - Eureka

    ReservationPilote:
      container_name: ReservationPiloteMicroservice
      build: ./ReservationPiloteMicroservice
      ports:
        - "8083:8083"
      hostname: ReservationPilote
      environment:
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      image: "auth-service"
      depends_on:
        - Eureka

    Gateway:
      container_name: api-gateway
      build: ./api-gateway
      ports:
        - "8762:8762"
      hostname: api-gateway
      environment:
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      image: "api-gateway"
      depends_on:
        - Eureka

    # node:
    #     container_name: node-service
    #     image: "node-service"
    #     build: ./node-service
    #     ports:
    #       - "3000:5000"
    #     hostname: node-service
    #     environment:
    #       - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=eureka-server
    #     depends_on:
    #       - "Eureka"


    #     command: "node ./index.js"
    Eureka:
      container_name: eureka-server
      build: ./eureka-server
      ports:
        - "8761:8761"
      hostname: eureka-server
      image: "eureka-server"
      environment:   
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/